[project]
name = "graph-pancake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "gliner==0.2.13",
    "keybert>=0.8.5",
    "langchain-core>=0.3.29",
    "numpy>=1.26.4",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]

[tool.ruff.lint]
select = ["E", "F", "I", "T201"]

[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]
langchain-chroma = { git = "https://github.com/langchain-ai/langchain.git", subdirectory = "libs/partners/chroma" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "cassandra-driver>=3.29.2",
    "cassio>=0.1.10",
    "langchain-astradb>=0.5.2",
    "langchain-chroma",
    "langchain-community>=0.3.14",
    "langchain-openai>=0.2.14",
    "langchain-opensearch>=0.0.2",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "sentence-transformers>=3.3.1",
]


