[project]
name = "graph-rag-example-helpers"
version = "0.1.0"
description = "Helpers for Graph RAG / Graph Retriever examples."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]

keywords = [
    "graph RAG",
    "RAG",
]

classifiers = [
    "Development Status :: 4 - Beta",

    # Supported Python Versions
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    # Topic
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",

    # Intended Audience(s)
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",

    # License
    "License :: OSI Approved :: Apache Software License",

    # Other Details
    "Operating System :: OS Independent",
]

dependencies = [
    "astrapy>=1.5.2",
    "backoff>=2.2.1",
    "httpx>=0.28.1",
    "langchain-core>=0.3.29",
    "python-dotenv>=1.0.1",
    "simsimd>=6.2.1",
    "tqdm>=4.67.1",
]

[tool.deptry.package_module_name_map]
astrapy = "astrapy"
backoff = "backoff"
httpx = "httpx"
langchain-core = "langchain_core"
mypy = "mypy"
networkx-stubs = "networkx_stubs"
pytest = "pytest"
pytest-asyncio = "pytest_asyncio"
pytest-cov = "pytest_cov"
python-dotenv = "dotenv"
simsimd = "simsimd"
tqdm = "tqdm"

[tool.deptry.per_rule_ignores]
DEP001 = ["google"]
DEP002 = ["simsimd"]

[project.urls]
"Homepage" = "https://datastax.github.io/graph-rag"
"GitHub" = "https://github.com/datastax/graph-rag"
"Bug Reports" = "https://github.com/datastax/graph-rag/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "networkx-stubs>=0.0.1",
    "pytest>=8.3.4",
    "pytest-cov>=4.0.0",
    "pytest-asyncio>=0.25.2",
]

