quartodoc:
  package: null
  style: pkgdown
  render_interlinks: true
  renderer:
    style: markdown
    table_style: description-list
  rewrite_all_pages: true
  options:
    include_attributes: true
  title: 'API Reference'
  sidebar:
    file: "reference/_sidebar.yml"
    style: docked
    search: true
    collapse-level: 4
    id: "reference"
    contents:
      - "{{ contents }}"
  sections:
  - title: graph_retriever
    desc: |
      Base package providing traversal functionality.
    package: graph_retriever
    contents:
    - name: traverse
    - name: atraverse
    - name: Adapter
    - name: Content
    - name: Edge
    - name: Edges
    - name: EdgeSpec
    - name: EdgeFunction
    - name: Id
    - name: IdEdge
    - name: MetadataEdge
    - name: Node
  - subtitle: 'edges'
    contents:
    - name: MetadataEdgeFunction
      package: 'graph_retriever.edges:metadata'
  - subtitle: 'strategies'
    contents:
    - name: Eager
      package: 'graph_retriever.strategies:eager'
    - name: Mmr
      package: 'graph_retriever.strategies:mmr'
    - name: Strategy
      package: 'graph_retriever.strategies'
  - title: langchain_graph_retriever
    desc: |
      Traversal functionality integrated as a LangChain retriever supporting a variety of LangChain `VectorStore`s.
    package: langchain_graph_retriever
    contents:
    - name: GraphRetriever
    - name: document_graph
  - subtitle: 'document_transformers'
    contents:
    - name: GLiNEREntityExtractor
      package: 'langchain_graph_retriever.document_transformers:gliner'
    - name: HierarchyLinkExtractor
      package: 'langchain_graph_retriever.document_transformers:hierarchy'
    - name: HtmlHyperlinkExtractor
      package: 'langchain_graph_retriever.document_transformers:html_hyperlink'
    - name: KeybertKeywordExtractor
      package: 'langchain_graph_retriever.document_transformers:keybert'
    - name: MetadataDenormalizer
      package: 'langchain_graph_retriever.document_transformers:metadata_denormalizer'
    - name: SpacyNERTransformer
      package: 'langchain_graph_retriever.document_transformers:spacy'
  - subtitle: 'adapters'
    contents:
    - name: LangchainAdapter
      package: 'langchain_graph_retriever.adapters:langchain'
    - name: DenormalizedAdapter
      package: 'langchain_graph_retriever.adapters:langchain'
    - name: AstraAdapter
      package: 'langchain_graph_retriever.adapters:astra'
    - name: CassandraAdapter
      package: 'langchain_graph_retriever.adapters:cassandra'
    - name: ChromaAdapter
      package: 'langchain_graph_retriever.adapters:chroma'
    - name: InMemoryAdapter
      package: 'langchain_graph_retriever.adapters:in_memory'
    - name: OpenSearchAdapter
      package: 'langchain_graph_retriever.adapters:open_search'
    - name: 'inference'
      package: 'langchain_graph_retriever.adapters'
      members:
        - infer_adapter
  - title: graph_rag_example_helpers
    desc: |
      Helpers used in various examples and notebooks.
    package: graph_rag_example_helpers
    contents:
    - name: initialize_environment
    - name: Environment
  - subtitle: datasets
    contents:
    - name: aload_2wikimultihop
      package: 'graph_rag_example_helpers.datasets.wikimultihop:load'



